#!/usr/bin/env ruby

require 'jiragit'

STDIN.reopen('/dev/tty')

def previous_head
  ARGV[0]
end

def new_head
  ARGV[1]
end

def branch_switch?
  ARGV[2] == '1'
end

def current_branch
  `git symbolic-ref -q HEAD --short`.chomp
end

def query(message)
  print "#{message} > "
  STDIN.gets.chomp
end

def quit_if_detached_head
  exit(1) unless current_branch!=''
end


#quit_if_detached_head


#puts "Existing relations", js.relations(branch: current_branch).to_a

jira = query("Is there a JIRA Number?")

js = Jiragit::JiraStore.new("#{Jiragit::Git.repository_root}/.git/jira_store")
js.relate(jira: jira, branch: current_branch)


